- name: Install prereqs
  apt:
    pkg:
      - make
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - wget
      - curl
      - llvm
      - libncursesw5-dev
      - xz-utils
      - tk-dev
      - libxml2-dev
      - libxmlsec1-dev
      - libffi-dev
      - liblzma-dev
  become: true
  when: ansible_os_family == 'Debian'

- name: Install pyenv
  git:
    repo: https://github.com/pyenv/pyenv.git
    dest: "{{ pyenv_home_directory }}"
    clone: true
    update: true

- name: Install Python Interpreters
  shell: |
    pyenv install --skip-existing "{{ item }}"
  environment:
    PYENV_ROOT: "{{ pyenv_home_directory }}"
    PATH: "{{ pyenv_home_directory }}/bin:{{ pyenv_home_directory }}/shims:{{ ansible_env.PATH }}"
  args:
    creates: "{{ pyenv_home_directory }}/versions/{{ item }}/bin/python"
  with_items: "{{ pyenv_python_versions | default([]) + [pyenv_global_python] }}"

- name: Set Python Global Interpreter
  shell: |
    pyenv global {{ pyenv_global_python }}
  environment:
    PYENV_ROOT: "{{ pyenv_home_directory }}"
    PATH: "{{ pyenv_home_directory }}/bin:{{ pyenv_home_directory }}/shims:{{ ansible_env.PATH }}"
